services:
    ger.modernquote.listener:
        class: ger\modernquote\event\main_listener
        arguments:
            - '@request'
            - '@config'
            - '@user'
            - '@template'
            - '@content.visibility'
            - '@dbal.conn'
            - '@text_formatter.utils'
            - '@language'
        tags:
            - { name: event.listener }
